#!/bin/bash

# For CBZs downloaded with HakuNeko
# Ensure original folder of CBZs are in page-order when sorted alphabetically A-Z

ORIGWORKDIR=$(pwd)

if [[ -z $1 ]]; then
	PRINWORKDIR="$1"
else
	PRINWORKDIR="./"
fi

cd "$PRINWORKDIR"

mkdir cbz_working

for f in *.cbz
do
	DIR="./cbz_working/$f"
	unzip "$f" -d "$DIR"
	cd "$DIR"

	HEAD=$(basename "$f" .cbz)

	if [[ $HEAD == *":"* ]]; then
		HEAD=$(echo "$HEAD" | tr ":" "\n" | head -n 1)
	fi

	for g in *
	do
		mv "$g" "$HEAD"_"$g"
	done

	mv * ../
	cd ../../
	rmdir "$DIR"
done

cd cbz_working

zip -mr "combined.zip" *
mv "combined.zip" "combined.cbz"

mv combined.cbz "$ORIGWORKDIR/"

cd ..

rmdir cbz_working