#!/bin/bash

paper="A4"

if [ $# -eq 2 ] || [ $# -eq 3 ]
then
	if [ $# -eq 3 ]; then
		paper=$3
	fi

    # https://stackoverflow.com/a/14736593/3211506
	pages=$(strings < "$1" | sed -n 's|.*/Count -\{0,1\}\([0-9]\{1,\}\).*|\1|p' | sort -rn | head -n 1)

    pgArgs=""

    # Brace expansion doesn't work on variables
    for ((i=1;i<=$pages;i++)); do
        pgArgs="$pgArgs A$i B1"
    done

    pdftk A="$1" B="/home/sunyudong/scripts/pdftools/blank_$paper.pdf" cat $pgArgs output "$2"

else
	echo "Usage example: convertForDuplex src.pdf res.pdf [A4, Letter]"
	echo "Defaults to A4"
	exit $E_BADARGS
fi
